version: '3'
services:
  server:
    build: ./server
    image: "iwantbot/server"
    volumes:
     - ..:/iwant-bot-mount
    ports:
     - "8080:8080"
  database:
    build: ./database
    image: "iwantbot/database"
